import type { ExpoConfig } from 'expo/config';
const config: ExpoConfig = {
  owner: 'logicfool',
  name: 'Outpost',
  slug: 'outpost-valorant',
  version: '0.6.4',
  orientation: 'portrait',
  userInterfaceStyle: 'automatic',
  scheme: 'outpost',

  icon: './assets/icon.png',
  ios: {
    bundleIdentifier: 'app.outpost.valorant',
    buildNumber: '10',
    supportsTablet: true,
    icon: './assets/icon.png',
    infoPlist: {
      ITSAppUsesNonExemptEncryption: false,
      CADisableMinimumFrameDurationOnPhone: true,
      UIBackgroundModes: ['processing'],
      BGTaskSchedulerPermittedIdentifiers: ['com.expo.modules.backgroundtask.processing'],
    },
  },
  android: {
    package: 'app.outpost.valorant',
    versionCode: 10,
    allowBackup: false,

    blockedPermissions: [
      'android.permission.RECORD_AUDIO',
      'android.permission.CAMERA',
      'android.permission.SYSTEM_ALERT_WINDOW',
      'android.permission.READ_EXTERNAL_STORAGE',
      'android.permission.WRITE_EXTERNAL_STORAGE',
      'android.permission.READ_MEDIA_IMAGES',
      'android.permission.READ_MEDIA_VIDEO',
      'android.permission.READ_MEDIA_AUDIO',
      'android.permission.READ_CONTACTS',
      'android.permission.WRITE_CONTACTS',
      'android.permission.READ_SMS',
      'android.permission.SEND_SMS',
      'android.permission.REQUEST_INSTALL_PACKAGES',
      'android.permission.QUERY_ALL_PACKAGES',
      'android.permission.ACCESS_FINE_LOCATION',
      'android.permission.ACCESS_COARSE_LOCATION',
      'android.permission.SCHEDULE_EXACT_ALARM',
    ],
    icon: './assets/icon.png',
    adaptiveIcon: { foregroundImage: './assets/adaptive-icon.png', backgroundColor: '#1B212E' },
  },
  plugins: [
    ['expo-secure-store', { configureAndroidBackup: true }],
    ['expo-sqlite', { useSQLCipher: true }],
    'expo-notifications',
    'expo-image',
    'expo-background-task',
    'expo-status-bar',
    'expo-video',
  ],
  web: { bundler: 'metro', name: 'Outpost demo' },
  extra: {
    experimentalRiotClientAccess: true,
    dataMode: 'local-first',
    eas: { projectId: '1513294e-122e-4886-9d4b-0cace0e240e4' },
  },
};
export default config;
